# Generated by Django 5.2.5 on 2025-08-28 06:50

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JWTSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="id",
                    ),
                ),
                (
                    "device_agent",
                    models.CharField(max_length=250, verbose_name="User agent"),
                ),
                (
                    "device_ip",
                    models.CharField(max_length=16, verbose_name="Ip Address"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expired_at",
                    models.DateTimeField(verbose_name="Session expire date"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "session",
                "verbose_name_plural": "sessions",
                "ordering": ["-created_at"],
            },
        ),
    ]
