# Generated by Django 5.1.7 on 2025-04-28 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('token_family', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TokenFamilyBlacklist',
            new_name='BlacklistedTokenFamily',
        ),
    ]
