# Generated by Django 5.0.6 on 2025-03-19 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("token_blacklist", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blacklistedtoken",
            options={
                "verbose_name": "Blacklisted Token",
                "verbose_name_plural": "Blacklisted Tokens",
            },
        ),
        migrations.AlterModelOptions(
            name="outstandingtoken",
            options={
                "ordering": ("user",),
                "verbose_name": "Outstanding Token",
                "verbose_name_plural": "Outstanding Tokens",
            },
        ),
    ]
