# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-17 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('token_blacklist', '0004_auto_20171017_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outstandingtoken',
            name='jti',
        ),
    ]
