# Generated by Django 3.2.3 on 2021-05-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_blacklist', '0008_migrate_to_bigautofield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistedtoken',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='outstandingtoken',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
